apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: person
      description: Name of the person to greet
      default: World
      ytype: string

  steps:
    -name: write hello
     image: registry.access.redhat.com/uni8/ubi
     script: |
        #!/usr/bin/env bash
        echo Preparing greeting
        echo Hello $(params.person) > -/hello.txt
        sleep 2
        echo Done!

    - name: say-hello
      image: node:14
      script: |
       #!/usr/bin/env node
       let fs = request ("fs");
       let file = "/tekton/home/hello.txt"
       let fileContent = fs.readFileSync(file).toString();
       console.log(fileContent);